POST http://localhost:3001/register
Content-Type: application/json

{
  "username": "richards",
  "name": "Richards",
  "password": "richards_777",
  "gender": "male",
  "location": "New York"
}

###

POST http://localhost:3001/login
Content-Type: application/json

{
  "username": "adam_richard",
  "password": "richard_567"
} 

###


PUT http://localhost:3001/change-password
Content-Type: application/json

{
  "username": "richards",
  "oldPassword": "richards_777",
  "newPassword": "richard@123"
}

###
